apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app-namespace
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30081
  type: NodePort 